/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransmitRouteImport } from './routes/transmit'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TransmitRoute = TransmitRouteImport.update({
  id: '/transmit',
  path: '/transmit',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/contact': typeof ContactRoute
  '/lab': typeof LabRoute
  '/mission': typeof MissionRoute
  '/modules': typeof ModulesRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/transmit': typeof TransmitRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/contact': typeof ContactRoute
  '/lab': typeof LabRoute
  '/mission': typeof MissionRoute
  '/modules': typeof ModulesRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/transmit': typeof TransmitRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/contact': typeof ContactRoute
  '/lab': typeof LabRoute
  '/mission': typeof MissionRoute
  '/modules': typeof ModulesRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/transmit': typeof TransmitRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brain'
    | '/contact'
    | '/lab'
    | '/mission'
    | '/modules'
    | '/story'
    | '/timeline'
    | '/transmit'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/contact'
    | '/lab'
    | '/mission'
    | '/modules'
    | '/story'
    | '/timeline'
    | '/transmit'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/brain'
    | '/contact'
    | '/lab'
    | '/mission'
    | '/modules'
    | '/story'
    | '/timeline'
    | '/transmit'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainRoute: typeof BrainRoute
  ContactRoute: typeof ContactRoute
  LabRoute: typeof LabRoute
  MissionRoute: typeof MissionRoute
  ModulesRoute: typeof ModulesRoute
  StoryRoute: typeof StoryRoute
  TimelineRoute: typeof TimelineRoute
  TransmitRoute: typeof TransmitRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transmit': {
      id: '/transmit'
      path: '/transmit'
      fullPath: '/transmit'
      preLoaderRoute: typeof TransmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainRoute: BrainRoute,
  ContactRoute: ContactRoute,
  LabRoute: LabRoute,
  MissionRoute: MissionRoute,
  ModulesRoute: ModulesRoute,
  StoryRoute: StoryRoute,
  TimelineRoute: TimelineRoute,
  TransmitRoute: TransmitRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
